suppressPackageStartupMessages({
  library(devtools)
  library(data.table)
  library(dplyr)
  library(tidyr)
  library(readr)
  library(tibble)
  library(purrr)
  library(stringr)
  library(forcats)
  library(GenomicFeatures)
  library(Biostrings)
  library(shinyjs)
  library(shiny)
  library(shinythemes)
  library(shinydashboard)
  library(ORFik)
  library(GenomicRanges)
  library(rtracklayer)
  library(markdown)
  library(devtools)
  library(vsn)
  library(ggtranscript)
  library(patchwork)
  library(ggrepel)
  library(optparse)
})

options(shiny.maxRequestSize = 2097152000) # 2GB

source("R/functions.R")
