name: GenomeProt_env
channels:
  - conda-forge
  - bioconda
  - anaconda
  - r
  - defaults
dependencies:
  - cd-hit=4.8.1
  - samtools
  - salmon
  - gffread
  - gffcompare
  - minimap2=2.28
  - bcftools
  - tabix
  - python=3.9
  - pip
  - zip
  - r-base=4.5.3
  - r-optparse
  - r-rmarkdown
  - r-data.table
  - r-dplyr
  - r-tidyr
  - r-readr
  - r-purrr
  - r-tibble
  - r-stringr
  - r-stringi
  - r-shinyjs
  - r-shiny
  - r-shinydashboard
  - r-markdown
  - r-knitr
  - r-ggplot2
  - r-scales
  - r-reticulate
  - r-openxlsx
  - bioconductor-bambu
  - bioconductor-biostrings
  - bioconductor-genomicfeatures
  - bioconductor-genomicranges
  - bioconductor-mygene
  - bioconductor-orfik
  - bioconductor-rsamtools
  - bioconductor-rtracklayer
  - bioconductor-seqinfo
  - bioconductor-txdbmaker
  - bioconductor-tximport
  - bioconductor-bsgenome.hsapiens.ucsc.hg38
  - bioconductor-bsgenome.celegans.ucsc.ce11
  - bioconductor-bsgenome.dmelanogaster.ucsc.dm6
  - bioconductor-bsgenome.mmusculus.ucsc.mm39
  - bioconductor-bsgenome.rnorvegicus.ucsc.rn7
  - bioconductor-bsgenome.drerio.ucsc.danrer11

  - pip:
    - biopython==1.77
    - py-cdhit
    - peptides
    - pysam
    - vcfpy