name: GenomeProt_env
channels:
  - conda-forge
  - bioconda
  - anaconda
  - r
  - defaults
dependencies:
  - samtools
  - bcftools
  - salmon
  - gffread
  - gffcompare
  - minimap2
  - python=3.9
  - pip
  - r-base
  - r-biocmanager
  - r-optparse
  - r-dplyr
  - r-devtools
  - r-rmarkdown
  - r-data.table
  - r-tidyr
  - r-readr
  - r-tibble
  - r-purrr
  - r-forcats
  - r-stringr
  - r-stringi
  - r-shinyjs
  - r-shiny
  - r-shinythemes
  - r-shinydashboard
  - r-markdown
  - r-patchwork
  - r-ggrepel
  - r-gplots
  - r-reshape2
  - r-phylotools
  - r-scales
  - r-rcolorbrewer
  - bioconductor-bambu
  - bioconductor-genomicfeatures
  - bioconductor-biostrings
  - bioconductor-orfik
  - bioconductor-genomicranges
  - bioconductor-rtracklayer
  - bioconductor-vsn
  - bioconductor-mygene
  - bioconductor-tximport
  - bioconductor-rsamtools
  - bioconductor-bsgenome.hsapiens.ucsc.hg38
  - bioconductor-bsgenome.mmusculus.ucsc.mm39
  - pip:
    - biopython==1.77
    - py-cdhit
    - peptides